FROM python:3.8
ENV CGO_ENABLED=1
WORKDIR /app

LABEL maintainer = "efrainhpedraza@gmail.com"
LABEL description = "Image for the Real State App Nubi"

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get -y install netcat gcc postgresql \
    && apt-get clean

RUN apt-get update \
    && apt-get install -y binutils libproj-dev gdal-bin  

RUN pip install --upgrade pip

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY . /app