# Generated by Django 4.2.3 on 2023-07-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='Medellin', max_length=180, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_address',
            field=models.CharField(default='Loma de', max_length=150, verbose_name='Street Address'),
        ),
    ]
